---
title: "Final_Project"
output: html_document
---
```{r}
#Install packages for map making
install.packages("sf")
install.packages("terra")
install.packages("spData")
install.packages("spDataLarge")
install.packages("tmap", repos = c("https://r-tmap.r-universe.dev",
                                   "https://cloud.r-project.org"))
```

```{r}
library(tidyverse)
library(readr)
#Load packages for map making!
library(sf)
library(terra)
library(dplyr)
library(spData)
library(tmap)    # for static and interactive maps
library(leaflet) # for interactive maps
library(ggplot2) # tidyverse data visualization package
```

```{r}
#Load all factor data
child_maltreatment <- read_csv("child_maltreatment.csv")
crime <- read_csv("crime.csv")
diabetes_er_visits <- read_csv("diabetes_er_visits.csv")
domestic_violence <- read_csv("domestic_violence.csv")
drug_overdoses <- read_csv("drug_overdoses.csv")
education <- read_csv("education.csv")
median_household_income <- read_csv("median_household_income.csv")
teen_birth_rate <- read_csv("teen_birth_rate.csv")
revenue_sources <- read_csv("revenue_sources.csv")
uninsured_er_visits <- read_csv("uninsured_er_visits.csv")

#Load all data that will show which counties in MD are rural. Rural areas are defined as places with fewer than 5,000 people and 2,000 housing units, according to the USDA.
#https://www.ers.usda.gov/topics/rural-economy-population/rural-classifications

rural_counties <- read_csv("ruc_2023.csv")
#Filtered data for the entire country into a dataset with only Maryland's RUCC2023 data
rural_counties <- filter(rural_counties, State == "MD", Attribute == "RUCC_2023")
#Going to make a desperate attempt to visualize this data into a map
```
